default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['USERNAME'] || 'postgres' %>
  password: <%= ENV['PASSWORD'] || 'postgres' %>
  host: <%= ENV['PG_HOST'] || "localhost" %>
  port: <%= ENV['PG_PORT'] || "5432" %>

development:
  <<: *default
  database: yuanda_development
test:
  <<: *default
  database: yuanda_development
staging:
  <<: *default
  database: yuanda_development
production:
  <<: *default
  database: yuanda_development
